version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    allow:
      - dependency-type: "all"
    versioning-strategy: lockfile-only
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
      day: "monday"
