# Site settings
title: Documentation Center
email: hello@scalingo.com
description: > # this means to ignore newlines until "baseurl:"
  Scalingo Documentation Center
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://doc.scalingo.com"
twitter_username: ScalingoHQ
github_username:  Scalingo
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highlighter: rouge

permalink: /:categories/:slug

keep_files:
  - packs

defaults:
  - # set default layout on all pages
    scope:
      path: ""
      type: "posts" # in jekyll files outside of _posts are of type pages
    values:
      layout: "page"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc

toc:
  min_level: 2
  max_level: 3

exclude:
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - Procfile
  - config
  - node_modules
  - package.json
  - yarn.lock
  - tmp
  - app/javascript
  - Dockerfile
  - docker-compose.yml
  - _plugins
  - ld_library_path
  - redirections.yml
  - Rakefile
  - lib/tasks

array: [] # hack for creating array

highlighted:
  first_steps:
    - /platform/getting-started/first-steps
    - /platform/getting-started/troubleshooting-ssh
    - /platform/databases/intro
    - /platform/app/application-lifecycle-management
    - /platform/cli/start
    - /platform/app/domain
    - /platform/app/ssl
    - /platform/account/your-account
    - /platform/app/filesystem
    - /platform/getting-started/heroku-compatibility
  technologies:
    - name: Ruby on Rails
      url: /languages/ruby/rails/start
    - name: MeteorJS
      url: "/languages/meteorjs/start"
    - name: NodeJS
      url: "/languages/nodejs/start"
    - name: PHP
      url: "/languages/php/start"
    - name: Python
      url: "/languages/php/python"
    - name: Java
      url: "/languages/java/start"
  addons:
    - name: PostgreSQL
      url: "/addons/scalingo-postgresql/start"
    - name: MySQL
      url: "/addons/scalingo-mysql/start"
    - name: MongoDB
      url: "/addons/scalingo-mongodb/start"
    - name: Redis
      url: "/addons/scalingo-redis/start"
    - name: Elasticsearch
      url: "/addons/scalingo-elasticsearch/start"
    - name: InfluxDB
      url: "/addons/scalingo-influxdb/start"

extlinks:
  followed_domains: ["scalingo.com", "my.scalingo.com", "cli.scalingo.com", "blog.scalingo.com", "developers.scalingo.com"]
