# Site settings
title: Documentation Center
email: hello@scalingo.com
description: > # this means to ignore newlines until "baseurl:"
  Scalingo Documentation Center
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://doc.scalingo.com"
twitter_username: ScalingoHQ
github_username:  Scalingo
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
highlighter: rouge

permalink: /:categories/:title/

keep_files:
  - packs

defaults:
  - # set default layout on all pages
    scope:
      path: ""
      type: "posts" # in jekyll files outside of _posts are of type pages
    values:
      layout: "page"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc

toc:
  min_level: 2
  max_level: 3

exclude:
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - Procfile
  - config
  - node_modules
  - package.json
  - yarn.lock
  - tmp
  - app/javascript
  - Dockerfile
  - docker-compose.yml
  - _plugins

array: [] # hack for creating array

highlighted:
  technologies:
    - name: Ruby on Rails
      url: /languages/ruby/getting-started-with-rails/
    - name: MeteorJS
      url: "/languages/javascript/nodejs/getting-started-with-meteor/"
    - name: NodeJS
      url: "/languages/javascript/nodejs/getting-started-with-nodejs/"
    - name: PHP
      url: "/"
    - name: Python
      url: "/"
    - name: Java
      url: "/"
  addons:
    - name: PostgreSQL
      url: "/"
    - name: MySQL
      url: "/"
    - name: MongoDB
      url: "/"
    - name: Redis
      url: "/"
    - name: Elasticsearch
      url: "/"
    - name: InfluxDB
      url: "/"

extlinks:
  followed_domains: ["scalingo.com", "my.scalingo.com", "cli.scalingo.com", "blog.scalingo.com", "developers.scalingo.com"]
