# Site settings
title: Documentation Center
email: hello@scalingo.com
description: > # this means to ignore newlines until "baseurl:"
  Scalingo Documentation Center
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://doc.scalingo.com"
twitter_username: ScalingoHQ
github_username:  Scalingo
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highlighter: rouge

permalink: /:categories/:slug

source: src

keep_files:
  - packs

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc

toc:
  min_level: 2
  max_level: 3

exclude:
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - Procfile
  - config
  - node_modules
  - package.json
  - yarn.lock
  - tmp
  - app/javascript
  - Dockerfile
  - docker-compose.yml
  - _plugins
  - ld_library_path
  - redirections.yml
  - Rakefile
  - lib/tasks

array: [] # hack for creating array

highlighted:
  first_steps:
    - /platform/getting-started/first-steps
    - /platform/getting-started/troubleshooting-ssh
    - /platform/databases/intro
    - /platform/app/lifecycle-management
    - /platform/cli/start
    - /platform/app/domain
    - /platform/app/ssl
    - /platform/account/manage
    - /platform/app/filesystem
    - /platform/getting-started/heroku-compatibility
  technologies:
    - name: Ruby on Rails
      url: /languages/ruby/rails/start
    - name: MeteorJS
      url: "/languages/meteorjs/start"
    - name: NodeJS
      url: "/languages/nodejs/start"
    - name: PHP
      url: "/languages/php/start"
    - name: Python
      url: "/languages/python/start"
    - name: Java
      url: "/languages/java/start"
  databases:
    - name: PostgreSQL
      url: "/databases/postgresql/start"
    - name: MySQL
      url: "/databases/mysql/start"
    - name: MongoDB
      url: "/databases/mongodb/start"
    - name: Redis
      url: "/databases/redis/start"
    - name: Elasticsearch
      url: "/databases/elasticsearch/start"
    - name: InfluxDB
      url: "/databases/influxdb/start"
  addons:
    - name: OpenVPN
      url: "/addons/scalingo-openvpn/start"
    - name: VPN IPSec
      url: "/addons/scalingo-vpn-ipsec/start"
    - name: Docker Image
      url: "/addons/scalingo-docker-image/start"

samples:
  - url: ruby-rails
    name: Ruby/Rails
    logo: ruby-on-rails
  - url: ruby-sinatra
    name: Ruby/Sinatra
    logo: sinatra
  - url: go-martini
    name: Go/Martini
    logo: go
  - url: meteor
    name: MeteorJS
    logo: meteorjs
  - url: node-express
    name: NodeJS/Express
    logo: nodejs
  - url: node-nuxt
    name: NodeJS/Nuxt.js
    logo: nodejs
  - url: node-socketio
    name: NodeJS/Socket.IO
    logo: nodejs
  - url: scala-scalatra
    name: Scala/Scalatra
    logo: scala
  - url: php-laravel
    name: PHP/Laravel
    logo: php-laravel
  - url: laravel-mix
    name: PHP/Laravel Mix
    logo: php-laravel
  - url: php-symfony
    name: PHP/Symfony
    logo: php-symfony
  - url: php-lumen
    name: PHP/Lumen
    logo: php-lumen
  - url: php
    name: PHP
    logo: php
  - url: php-cron
    name: PHP/Cron
    logo: php
  - url: php-nodejs
    name: PHP/NodeJS
    logo: php
  - url: php-yii2
    name: PHP/Yii 2
    logo: php-yii
  - url: php-slim
    name: PHP/Slim
    logo: php-slim
  - url: php-codeigniter
    name: PHP/CodeIgniter
    logo: php-codeigniter
  - url: python-celery
    name: Python/Celery
    logo: python
  - url: python-django
    name: Python/Django
    logo: python-django
  - url: python-flask
    name: Python/Flask
    logo: python-flask
  - url: elixir-plug
    name: Elixir/Plug
    logo: elixir
  - url: crystal
    name: Crystal
    logo: crystal
  - url: java-spark
    name: Java/Spark
    logo: java-spark
  - url: influxdb
    name: Go/InfluxDB
    logo: influxdb
  - url: java-grails3
    name: Java/Grails 3
    logo: groovy-grails
  - url: node-mosca
    name: NodeJS/Mosca/MQTT
    logo: mosca
  - url: kotlin
    name: Kotlin
    logo: kotlin
  - url: erlang
    name: Erlang
    logo: erlang

extlinks:
  followed_domains: ["scalingo.com", "my.scalingo.com", "cli.scalingo.com", "blog.scalingo.com", "developers.scalingo.com"]
