# Site settings
title: Documentation Center
email: hello@scalingo.com
description: > # this means to ignore newlines until "baseurl:"
  Scalingo Documentation Center
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://doc.scalingo.com"
twitter_username: ScalingoHQ
github_username:  Scalingo
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highlighter: rouge

permalink: /:categories/:slug

source: src

keep_files:
  - packs

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc

toc:
  min_level: 2
  max_level: 3

exclude:
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - Procfile
  - config
  - node_modules
  - package.json
  - yarn.lock
  - tmp
  - app/javascript
  - Dockerfile
  - docker-compose.yml
  - _plugins
  - ld_library_path
  - redirections.yml
  - Rakefile
  - lib/tasks

highlighted:
  first_steps:
    - /platform/getting-started/first-steps
    - /platform/getting-started/troubleshooting-ssh
    - /platform/databases/intro
  popular:
    - /platform/getting-started/first-steps
    - /platform/getting-started/troubleshooting-ssh
    - /platform/databases/intro
    - /platform/getting-started/first-steps
    - /platform/getting-started/troubleshooting-ssh
    - /platform/databases/intro
  technologies:
    - name: Ruby on Rails
      url: /languages/ruby/rails/start
      icon: ruby-on-rails
    - name: MeteorJS
      url: "/languages/meteorjs/start"
      icon: meteorjs
    - name: NodeJS
      url: "/languages/nodejs/start"
      icon: nodejs
  databases:
    - name: PostgreSQL
      url: "/databases/postgresql/start"
      icon: postgresql
    - name: MySQL
      url: "/databases/mysql/start"
      icon: mysql
    - name: MongoDB
      url: "/databases/mongodb/start"
      icon: mongodb

languages:
  - url: go
    name: "Go"
    logo: go
  - url: meteorjs
    name: "MeteorJS"
    logo: meteorjs
  - url: nodejs
    name: "Node.js"
    logo: nodejs
  - url: php
    name: "PHP"
    logo: php
  - url: groovy
    name: "Groovy"
    logo: groovy
  - url: java
    name: "Java"
    logo: java
  - url: clojure
    name: "Clojure"
    logo: clojure
  - url: crystal
    name: "Crystal"
    logo: crystal
  - url: elixir
    name: "Elixir"
    logo: elixir
  - url: erlang
    name: "Erlang"
    logo: erlang
  - url: python
    name: "Python"
    logo: python
  - url: ruby
    name: "Ruby"
    logo: ruby
  - url: scala
    name: "Scala"
    logo: scala

databases:
  - url: postgresql
    name: "PostgresSQL"
    logo: postgresql
  - url: mysql
    name: "MySQL"
    logo: mysql
  - url: mongodb
    name: "MongoDB"
    logo: mongodb
  - url: redis
    name: "Redis"
    logo: redis
  - url: elasticsearch
    name: "Elasticsearch"
    logo: elasticsearch
  - url: influxdb
    name: "InfluxDB"
    logo: influxdb

samples:
  - url: ruby-rails
    name: Ruby/Rails
    logo: ruby-on-rails
  - url: ruby-sinatra
    name: Ruby/Sinatra
    logo: sinatra
  - url: go-martini
    name: Go/Martini
    logo: go
  - url: meteor
    name: MeteorJS
    logo: meteorjs
  - url: node-express
    name: NodeJS/Express
    logo: nodejs
  - url: node-nuxt
    name: NodeJS/Nuxt.js
    logo: nodejs
  - url: node-socketio
    name: NodeJS/Socket.IO
    logo: nodejs
  - url: scala-scalatra
    name: Scala/Scalatra
    logo: scala
  - url: php-laravel
    name: PHP/Laravel
    logo: php-laravel
  - url: laravel-mix
    name: PHP/Laravel Mix
    logo: php-laravel
  - url: php-symfony
    name: PHP/Symfony
    logo: php-symfony
  - url: php-lumen
    name: PHP/Lumen
    logo: php-lumen
  - url: php
    name: PHP
    logo: php
  - url: php-cron
    name: PHP/Cron
    logo: php
  - url: php-nodejs
    name: PHP/NodeJS
    logo: php
  - url: php-yii2
    name: PHP/Yii 2
    logo: php-yii
  - url: php-slim
    name: PHP/Slim
    logo: php-slim
  - url: php-codeigniter
    name: PHP/CodeIgniter
    logo: php-codeigniter
  - url: python-celery
    name: Python/Celery
    logo: python
  - url: python-django
    name: Python/Django
    logo: python-django
  - url: python-flask
    name: Python/Flask
    logo: python-flask
  - url: elixir-plug
    name: Elixir/Plug
    logo: elixir
  - url: crystal
    name: Crystal
    logo: crystal
  - url: java-spark
    name: Java/Spark
    logo: java-spark
  - url: influxdb
    name: Go/InfluxDB
    logo: influxdb
  - url: java-grails3
    name: Java/Grails 3
    logo: groovy-grails
  - url: node-mosca
    name: NodeJS/Mosca/MQTT
    logo: mosca
  - url: kotlin
    name: Kotlin
    logo: kotlin
  - url: erlang
    name: Erlang
    logo: erlang

extlinks:
  followed_domains:
    - "scalingo.com"
    - "my.scalingo.com"
    - "dashboard.scalingo.com"
    - "cli.scalingo.com"
    - "blog.scalingo.com"
    - "developers.scalingo.com"
