# Site settings
title: Documentation Center
email: hello@scalingo.com
description: > # this means to ignore newlines until "baseurl:"
  Scalingo Documentation Center
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://doc.scalingo.com"
twitter_username: ScalingoHQ
github_username:  Scalingo
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highlighter: rouge

permalink: /:categories/:slug

keep_files:
  - packs

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "changelog"
      type: "posts"
    values:
      layout: "changelog_entry"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc

toc:
  min_level: 2
  max_level: 3

exclude:
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - Procfile
  - config
  - node_modules
  - package.json
  - yarn.lock
  - tmp
  - app/javascript
  - Dockerfile
  - docker-compose.yml
  - _plugins
  - ld_library_path
  - redirections.yml
  - Rakefile
  - lib/tasks

array: [] # hack for creating array

highlighted:
  first_steps:
    - /platform/getting-started/first-steps
    - /platform/getting-started/troubleshooting-ssh
    - /platform/databases/intro
    - /platform/app/lifecycle-management
    - /platform/cli/start
    - /platform/app/domain
    - /platform/app/ssl
    - /platform/account/manage
    - /platform/app/filesystem
    - /platform/getting-started/heroku-compatibility
  technologies:
    - name: Ruby on Rails
      url: /languages/ruby/rails/start
    - name: MeteorJS
      url: "/languages/meteorjs/start"
    - name: NodeJS
      url: "/languages/nodejs/start"
    - name: PHP
      url: "/languages/php/start"
    - name: Python
      url: "/languages/php/python"
    - name: Java
      url: "/languages/java/start"
  addons:
    - name: PostgreSQL
      url: "/addons/scalingo-postgresql/start"
    - name: MySQL
      url: "/addons/scalingo-mysql/start"
    - name: MongoDB
      url: "/addons/scalingo-mongodb/start"
    - name: Redis
      url: "/addons/scalingo-redis/start"
    - name: Elasticsearch
      url: "/addons/scalingo-elasticsearch/start"
    - name: InfluxDB
      url: "/addons/scalingo-influxdb/start"

samples:
  - url: sample-ruby-sinatra
    name: Ruby/Sinatra
    logo: sinatra
  - url: sample-go-martini
    name: Go/Martini
    logo: go
  - url: sample-meteor-todo
    name: MeteorJS
    logo: meteorjs
  - url: sample-node-express
    name: NodeJS/Express
    logo: nodejs
  - url: sample-node-meanjs
    name: NodeJS/MeanJS
    logo: mean-js
  - url: sample-scala-scalatra
    name: Scala/Scalatra
    logo: scala
  - url: sample-php-laravel
    name: PHP/Laravel
    logo: php-laravel
  - url: sample-php-symfony
    name: PHP/Symfony
    logo: php-symfony
  - url: sample-php-lumen
    name: PHP/Lumen
    logo: php-lumen
  - url: sample-php-base
    name: PHP
    logo: php
  - url: sample-php-cron
    name: PHP/Cron
    logo: php
  - url: sample-php-nodejs
    name: PHP/NodeJS
    logo: php
  - url: sample-php-yii2
    name: PHP/Yii 2
    logo: php-yii
  - url: sample-php-slim
    name: PHP/Slim
    logo: php-slim
  - url: sample-python-celery
    name: Python/Celery
    logo: python
  - url: sample-python-flask
    name: Python/Flask
    logo: python-flask
  - url: sample-python2-flask
    name: Python 2/Flask
    logo: python-flask
  - url: sample-crystal
    name: Crystal
    logo: crystal
  - url: sample-java-spark
    name: Java/Spark
    logo: java-spark
  - url: sample-influxdb
    name: Go/InfluxDB
    logo: scalingo-influxdb
  - url: sample-java-grails3
    name: Java/Grails 3
    logo: groovy-grails

extlinks:
  followed_domains: ["scalingo.com", "my.scalingo.com", "cli.scalingo.com", "blog.scalingo.com", "developers.scalingo.com"]
