version: '2'
services:
  web:
    build: .
    # links:
    #   - webpack
    ports:
      - 4300:4300
      - 4302:4302
    volumes:
      - ./:/usr/src/app
    environment:
      AUTH_API_BASE_URI: "https://api.scalingo.com/"
      API_BASE_URI: "https://api.scalingo.com/"
      BLOG_ROOT_URL: "https://blog.scalingo.io"
      REDIS_URL: "redis://:pipo@redis:6379"
      BUNDLE_BIN: "/usr/src/app/vendor/.bundle/ruby/3.0.0/bin"
      BUNDLE_PATH: "/usr/src/app/vendor/.bundle/ruby/3.0.0"
      JEKYLL_ENV: "development"
    command: bundle exec jekyll serve --watch --host 0.0.0.0 --port 4300 --trace --incremental --livereload --livereload-port 4302
  webpack:
    build: .
    ports:
      - 4301:4301
    volumes:
      - ./:/usr/src/app
    command: bin/webpack-dev-server --config config/webpack/development.js
    environment:
      NODE_ENV: "development"
      RAILS_ENV: "development"
      BUNDLE_BIN: "/usr/src/app/vendor/.bundle/ruby/3.0.0/bin"
      BUNDLE_PATH: "/usr/src/app/vendor/.bundle/ruby/3.0.0"
  tailwind:
    build: .
    volumes:
      - ./:/usr/src/app
    command: yarn build:css --watch --verbose
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: "development"
      RAILS_ENV: "development"
      BUNDLE_BIN: "/usr/src/app/vendor/.bundle/ruby/3.0.0/bin"
      BUNDLE_PATH: "/usr/src/app/vendor/.bundle/ruby/3.0.0"
